# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cliente.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'cliente.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcliente.proto\x12\x07\x63liente\x1a\x1bgoogle/protobuf/empty.proto\"\xb8\x01\n\rCompraRequest\x12\x17\n\x0fnombre_producto\x18\x01 \x01(\t\x12\x0e\n\x06precio\x18\x02 \x01(\x01\x12\x15\n\rcliente_email\x18\x03 \x01(\t\x12\x13\n\x0bmetodo_pago\x18\x04 \x01(\t\x12\r\n\x05\x62\x61nco\x18\x05 \x01(\t\x12\x14\n\x0ctipo_tarjeta\x18\x06 \x01(\t\x12\r\n\x05\x63\x61lle\x18\x07 \x01(\t\x12\x0e\n\x06numero\x18\x08 \x01(\t\x12\x0e\n\x06region\x18\t \x01(\t\"!\n\x0e\x43ompraResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t2L\n\x07\x43liente\x12\x41\n\x0eRealizarCompra\x12\x16.cliente.CompraRequest\x1a\x17.cliente.CompraResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cliente_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPRAREQUEST']._serialized_start=56
  _globals['_COMPRAREQUEST']._serialized_end=240
  _globals['_COMPRARESPONSE']._serialized_start=242
  _globals['_COMPRARESPONSE']._serialized_end=275
  _globals['_CLIENTE']._serialized_start=277
  _globals['_CLIENTE']._serialized_end=353
# @@protoc_insertion_point(module_scope)
